# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BPYRaxSbiAdWRRMCXf7uGdPfm_bHLu8
"""

import torch
import torch.nn as nn
import numpy as np
import random

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

text = """
artificial intelligence is transforming modern society.
it is used in healthcare finance education and transportation.
machine learning allows systems to improve automatically with experience.
data plays a critical role in training intelligent systems.
large datasets help models learn complex patterns.
deep learning uses multi layer neural networks.
neural networks are inspired by biological neurons.
each neuron processes input and produces an output.
training a neural network requires optimization techniques.
gradient descent minimizes the loss function.

natural language processing helps computers understand human language.
text generation is a key task in nlp.
language models predict the next word or character.
recurrent neural networks handle sequential data.
lstm and gru models address long term dependency problems.
however rnn based models are slow for long sequences.

transformer models changed the field of nlp.
they rely on self attention mechanisms.
attention allows the model to focus on relevant context.
transformers process data in parallel.
this makes training faster and more efficient.
modern language models are based on transformers.

education is being improved using artificial intelligence.
intelligent tutoring systems personalize learning.
automated grading saves time for teachers.
online education platforms use recommendation systems.
technology enhances the quality of learning experiences.

ethical considerations are important in artificial intelligence.
fairness transparency and accountability must be ensured.
ai systems should be designed responsibly.
data privacy and security are major concerns.
researchers continue to improve ai safety.

text generation models can create stories poems and articles.
they are used in chatbots virtual assistants and content creation.
generated text should be meaningful and coherent.
evaluation of text generation is challenging.
human judgement is often required.

continuous learning is essential in the field of ai.
research and innovation drive technological progress.
students should build strong foundations in mathematics.
programming skills are important for ai engineers.
practical experimentation enhances understanding.
"""

chars = sorted(list(set(text)))
vocab_size = len(chars)

char2idx = {ch:i for i,ch in enumerate(chars)}
idx2char = {i:ch for ch,i in char2idx.items()}

encoded_text = [char2idx[c] for c in text]

seq_length = 50
X = []
Y = []

for i in range(len(encoded_text) - seq_length):
    X.append(encoded_text[i:i+seq_length])
    Y.append(encoded_text[i+1:i+seq_length+1])

X = torch.tensor(X).to(device)
Y = torch.tensor(Y).to(device)

class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_size=64, hidden_size=128):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        out, _ = self.lstm(x)
        out = self.fc(out)
        return out

model = LSTMModel(vocab_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.003)

epochs = 20

for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()

    output = model(X)

    loss = criterion(output.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

def generate_text(seed, length=300):
    model.eval()
    result = seed
    input_seq = torch.tensor([char2idx[c] for c in seed]).unsqueeze(0).to(device)

    for _ in range(length):
        output = model(input_seq)
        last_char_logits = output[0, -1]
        prob = torch.softmax(last_char_logits, dim=0)
        char_idx = torch.multinomial(prob, 1).item()

        result += idx2char[char_idx]
        input_seq = torch.cat([input_seq[:,1:], torch.tensor([[char_idx]]).to(device)], dim=1)

    return result

print(generate_text("artificial intelligence "))

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=500):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-np.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        self.pe = pe.unsqueeze(0)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)].to(x.device)

class TransformerModel(nn.Module):
    def __init__(self, vocab_size, d_model=128, nhead=4, num_layers=2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoder = PositionalEncoding(d_model)

        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.fc = nn.Linear(d_model, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = self.pos_encoder(x)
        x = x.permute(1,0,2)
        x = self.transformer(x)
        x = x.permute(1,0,2)
        return self.fc(x)

transformer_model = TransformerModel(vocab_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(transformer_model.parameters(), lr=0.003)

epochs = 20

for epoch in range(epochs):
    transformer_model.train()
    optimizer.zero_grad()

    output = transformer_model(X)
    loss = criterion(output.view(-1, vocab_size), Y.view(-1))

    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

def generate_text_transformer(seed, length=300):
    transformer_model.eval()
    result = seed
    input_seq = torch.tensor([char2idx[c] for c in seed]).unsqueeze(0).to(device)

    for _ in range(length):
        output = transformer_model(input_seq)
        last_char_logits = output[0, -1]
        prob = torch.softmax(last_char_logits, dim=0)
        char_idx = torch.multinomial(prob, 1).item()

        result += idx2char[char_idx]
        input_seq = torch.cat([input_seq[:,1:], torch.tensor([[char_idx]]).to(device)], dim=1)

    return result

print(generate_text_transformer("transformer models "))